---
- name: Provision Consul container image
  hosts: packer

  vars_files:
    # Control node configuration file
    - "{{ playbook_dir }}/../../../ryo-control-node/configuration/configuration.yml"
    # Module configuration file
    - "{{ playbook_dir }}/../../configuration/configuration.yml"

  roles:
    - role: upgrade-container
    - role: install-iptables
    - role: install-cron
    - role: install-coturn
    - role: install-consul
    - role: install-unzip
    - role: install-consul-template
    - role: set-up-firewall
    - role: set-up-consul
    - role: set-up-coturn
    - role: set-up-consul-template
