---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later


# Create directory for consul-template configuration files
#
- name: Create directory for consul-template configuration files
  file:
    path: /etc/consul-template
    state: directory
    mode: 0755


# Copy consul-template configuration file
#
- name: Copy consul-template configuration file
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /etc/consul-template/consul-template-config.hcl
    src: consul-template-config.hcl
    force: yes


# Copy consul-template template file for dynamic coturn configuration based on consul key-values
#
- name: Copy consul-template template file for dynamic coturn configuration
  template:
    mode: 0644
    owner: root
    group: root
    dest: /etc/consul-template/turnserver.conf.ctmpl
    src: turnserver.conf.ctmpl.j2
    force: yes


# Copy consul-template template file for dynamic nftables configuration based on consul key-values
#
- name: Copy consul-template template file for dynamic nftables configuration
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /etc/consul-template/nftables.ctmpl
    src: nftables.ctmpl
    force: yes


# Copy consul-template template file for provisioning ryo-ingress-proxy for coturn
#
- name: Copy consul-template template file for dynamic ryo-ingress-proxy configuration
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /etc/consul-template/configure-ingress-proxy.sh.ctmpl
    src: configure-ingress-proxy.sh.ctmpl
    force: yes


# Copy script to execute provisioning of ryo-ingress-proxy for coturn
#
- name: Copy script to execute provisioning of ryo-ingress-proxy for coturn
  copy:
    mode: 0755
    owner: root
    group: root
    dest: /usr/local/bin/execute-configure-ingress-proxy.sh
    src: execute-configure-ingress-proxy.sh
    force: yes


# Copy consul-template service definition
#
- name: Copy consul-template service definition
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /lib/systemd/system/consul-template.service
    src: consul-template.service
    force: yes


# Enable consul-template service
#
- name: Enable consul-template service
  service:
    name: consul-template.service
    enabled: yes
    state: stopped
