#-----------------------
# REQUIRED Configuration
#-----------------------

# Basic module configuration
#---------------------------

# Do not change these values unless you know what you are doing 
module_id: ryo-coturn
coturn_ip_addr_host_part: 15